const animals = [
  {
    id: 1,
    name: 'Stokstaartje',
    habitat: 'Zuid-Afrika',
    imageUrl: '/images/stokstaartje.jpg',
    diet: 'insectivoor',
    description: 'Stokstaartjes zijn sociale dieren die in groepen leven en bekend staan om hun rechtopstaande houding.',
  },
  {
    id: 2,
    name: 'Olifant',
    habitat: 'Savanne, Bossen',
    imageUrl: '/images/olifant.jpg',
    diet: 'herbivoor',
    description: 'Olifanten zijn de grootste landdieren en zijn bekend om hun intelligentie en sociale structuren.',
  },
  {
    id: 3,
    name: 'Giraffe',
    habitat: 'Savanne',
    imageUrl: '/images/giraffe.jpg',
    diet: 'herbivoor',
    description: 'Giraffen zijn de hoogste landdieren met lange nekken die hen helpen bladeren van hoge bomen te eten.',
  },
  {
    id: 4,
    name: 'Tijger',
    habitat: 'Bos',
    imageUrl: '/images/tijger.jpg',
    diet: 'carnivoor',
    description: 'Tijgers zijn krachtige jagers en het grootste lid van de kattenfamilie.',
  },
  {
    id: 5,
    name: 'Panda',
    habitat: 'Bamboebossen',
    imageUrl: '/images/panda.png',
    diet: 'herbivoor',
    description: 'De panda staat bekend om zijn zwart-witte vacht en is beroemd om zijn liefde voor bamboe.',
  },
  {
    id: 6,
    name: 'Leeuw',
    habitat: 'Savanne',
    imageUrl: '/images/leeuw.jpg', 
    diet: 'carnivoor',
    description: 'De leeuw is een groot, sociaal zoogdier en staat bekend als de koning van de jungle.',
  },
  {
    id: 7,
    name: 'Kangoeroe',
    habitat: 'Australische Bossen',
    imageUrl: '/images/kangoeroe.jpg',
    diet: 'herbivoor',
    description: 'Kangoeroes zijn iconische Australiërs en staan bekend om hun krachtige achterpoten en zak.',
  },
  {
    id: 8,
    name: 'Wolf',
    habitat: 'Bossen',
    imageUrl: '/images/wolf.webp',
    diet: 'carnivore',
    description: 'Wolven zijn sociale jagers die in roedels leven en communiceren met een scala aan vocalisaties.',
  },
  {
    id: 9,
    name: 'Eland',
    habitat: 'Bos en Toendra',
    imageUrl: '/images/eland.jpg',
    diet: 'herbivoor',
    description: 'Elanden zijn de grootste herten, met grote, brede schoffels en zijn bekend om hun rustieke, majestueuze uitstraling.',
  },
];

export default animals;
